version: '2'

services:
  <%= name %>:
    build: .
    command: npm run dev -- --port <%= port %>
    environment:
      - LOGSTASH_SERVICE_HOST=logstash
      - LOGSTASH_SERVICE_PORT=5000
      - NODE_ENV=production
    links:
      - logstash
    ports:
      - "<%= port %>:<%= port %>"
    volumes:
      - ./service/src:/service/src
  elasticsearch:
    image: hharnisc/elasticsearch:v1
    expose:
      - "9200"
  logstash:
    image: hharnisc/logstash:v2
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    expose:
      - "5000"
    links:
      - elasticsearch
  kibana:
    image: hharnisc/kibana:v1
    ports:
      - "5601:5601"
    links:
      - elasticsearch
